name: C++ Build and Test

on:
  push:
    branches: [ master, main ]
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'src/**'
      - 'CMakeLists.txt'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
        
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16'
        
    - name: Configure CMake
      run: cmake -B build -S src -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
      
    - name: Test Protocol
      run: |
        cd build
        if [ "$RUNNER_OS" == "Windows" ]; then
          ./harmonic_protocol.exe
        else
          ./harmonic_protocol
        fi
      shell: bash
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: harmonic-protocol-${{ matrix.os }}-${{ matrix.build_type }}
        path: build/harmonic_protocol*
        retention-days: 7
